### ISSUE TITLE
error incorrect argument

### ISSUE THREAD

**Issue by bgobi1991** [francisdaigle/node-wkhtmltopdf#3]
TypeError: Incorrect value of args option
    at exports.spawn (child_process.js:725:11)
    at wkhtmltopdf (D:\Angular Example\wkhtmlpdf\lib\wkhtmltopdf.js:31:17)
    at Server.handleRequest (D:\Angular Example\wkhtmlpdf\test\server.js:37:15)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2113:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23
    at Socket.socket.ondata (http.js:1971:22)
    at TCP.onread (net.js:528:27)

**Comment by francisdaigle** [comment]
Sorry for the late response – I was away on vacation.

Did you resolve your problem?
If not, can you provide more information as to how this error was generated? 
What OS are you using? 
Did you try using the URL provided in the "README"?
