### ISSUE TITLE
TypeError: Incorrect value of args option

### ISSUE THREAD

**Issue by parisambush** [francisdaigle/node-wkhtmltopdf#6]
I'm getting the following error when I run the script:

TypeError: Incorrect value of args option
   at normalizeSpawnArguments (child_process.js:959:11)
   at exports.spawn (child_process.js:991:38)
   at wkhtmltopdf (C:\Dev\uapdfnodeweb\node_modules\node-wkhtmltopdf\lib\wkhtmltopdf.js:31:17)
   at module.exports (C:\Dev\uapdfnodeweb\controllers\pdf-gen.js:18:15)
   at C:\Dev\uapdfnodeweb\routes\index.js:8:9
   at Layer.handle [as handle_request](C:Devuapdfnodewebnode_modulesexpresslibrouterlayer.js:95:5)
   at next (C:\Dev\uapdfnodeweb\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\Dev\uapdfnodeweb\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request](C:Devuapdfnodewebnode_modulesexpresslibrouterlayer.js:95:5)
   at C:\Dev\uapdfnodeweb\node_modules\express\lib\router\index.js:277:22

It appears that the problem is when you spawn the child process at line 31 of wkhtmltopdf.js, you are passing the arguments as a string instead of an array. Then what happens as a result is an error is thrown during the argument normalization process on line 958 of child_process.js. 

I'm running this on Windows 7. The same thing likely happens on Linux systems, but I haven't tested there.

**Comment by francisdaigle** [comment]
Sorry - must have missed this :/ 

Were you able to resolve your issue?

**Comment by x1911** [comment]
i have the same issue, only in windows system,

this lib works fine in osx

**Comment by francisdaigle** [comment]
@x1911: Were you able to resolve your issue?

**Comment by x1911** [comment]
it seems wkhtmltopdf not running in windows, 

so i put the wkhtmltopdf direction in windows system setting "PATH"

and restart it.

so it works
